"""ARAC action library: ActionSpec interface and semantic-surface modules."""

from .action_spec import ActionSpec
from .controller_profiles import (
    CONTROLLER_PROFILES,
    ControllerProfile,
    controller_action_effects,
    controller_has_capability,
    controller_profile_by_action,
    controller_profile_by_lane,
    controller_profile_by_version,
)
from .shared_variable_blend import (
    NATIVE_EQ8_ACTION,
    SHARED_VARIABLE_ACTION_SPECS,
    TRUE_NO_WRITEBACK_ACTION,
    apply_legacy_shared_variable_policy,
    apply_shared_variable_action,
    blend_overlap_values,
    clipped_consensus_blend,
)
from .budget_reallocation import (
    BUDGET_REALLOCATION_ACTION_SPECS,
    FROZEN_BUDGET_MAX_UNIFORM_MULTIPLIER,
    FROZEN_EFFICIENCY_BUDGET_REALLOCATION_ACTION,
    BudgetAllocationAction,
    BudgetAllocationExecutionState,
    apply_budget_reallocation_action,
    budget_allocation_anchor_hash,
    budget_allocation_parameter_hash,
    execute_budget_allocation_action,
)
from .persistent_budget_reallocation import (
    PERSISTENT_BUDGET_REALLOCATION_ACTION_SPEC,
    PERSISTENT_EFFICIENCY_BUDGET_REALLOCATION_ACTION,
    PersistentBudgetAllocationAction,
    PersistentBudgetAllocationExecutionState,
    PersistentBudgetApplication,
    execute_persistent_budget_allocation_action,
)
from .sweep_ordering import (
    SWEEP_ORDERING_ACTION_SPECS,
    apply_sweep_ordering_action,
)
from .warm_start import (
    WARM_START_ACTION_SPECS,
    apply_warm_start_action,
)
from .group_optimizer_type import (
    DIAGONAL_COVARIANCE_MODE,
    FULL_CMAES_MODE,
    GROUP_OPTIMIZER_MODES,
    GroupOptimizerAction,
    resolve_group_optimizer_action,
)
from .full_space_sep_cma import (
    CANONICAL_SEP_CMA_PARAMETERIZATION,
    CANONICAL_SEP_CMA_PARAMETERS_HASH,
    CANONICAL_SEP_CMA_POPULATION_SIZE,
    CANONICAL_SEP_CMA_REFERENCE_VERSION,
    FULL_SPACE_DIMENSION,
    FULL_SPACE_SEP_CMA_ACTION,
    FULL_SPACE_SEP_CMA_ACTION_SPEC,
    FULL_SPACE_SEP_CMA_BURST_SEED_NAMESPACE,
    FullSpaceSepCmaAction,
    FullSpaceSepCmaExecutionContext,
    FullSpaceSepCmaExecutionResult,
    FullSpaceSepCmaExecutionState,
    execute_full_space_sep_cma_action,
    full_space_sep_cma_anchor_hash,
    full_space_vector_hash,
)
from .runtime_dispatcher import (
    DEFAULT_RUNTIME_ACTION_DISPATCHER,
    RuntimeActionDispatcher,
    UnsupportedRuntimeActionError,
)

__all__ = [
    "ActionSpec",
    "BUDGET_REALLOCATION_ACTION_SPECS",
    "BudgetAllocationAction",
    "BudgetAllocationExecutionState",
    "CONTROLLER_PROFILES",
    "ControllerProfile",
    "CANONICAL_SEP_CMA_PARAMETERIZATION",
    "CANONICAL_SEP_CMA_PARAMETERS_HASH",
    "CANONICAL_SEP_CMA_POPULATION_SIZE",
    "CANONICAL_SEP_CMA_REFERENCE_VERSION",
    "DIAGONAL_COVARIANCE_MODE",
    "FULL_CMAES_MODE",
    "FULL_SPACE_DIMENSION",
    "FULL_SPACE_SEP_CMA_ACTION",
    "FULL_SPACE_SEP_CMA_ACTION_SPEC",
    "FULL_SPACE_SEP_CMA_BURST_SEED_NAMESPACE",
    "FROZEN_BUDGET_MAX_UNIFORM_MULTIPLIER",
    "FROZEN_EFFICIENCY_BUDGET_REALLOCATION_ACTION",
    "GROUP_OPTIMIZER_MODES",
    "FullSpaceSepCmaAction",
    "FullSpaceSepCmaExecutionContext",
    "FullSpaceSepCmaExecutionResult",
    "FullSpaceSepCmaExecutionState",
    "GroupOptimizerAction",
    "NATIVE_EQ8_ACTION",
    "PERSISTENT_BUDGET_REALLOCATION_ACTION_SPEC",
    "PERSISTENT_EFFICIENCY_BUDGET_REALLOCATION_ACTION",
    "PersistentBudgetAllocationAction",
    "PersistentBudgetAllocationExecutionState",
    "PersistentBudgetApplication",
    "SHARED_VARIABLE_ACTION_SPECS",
    "SWEEP_ORDERING_ACTION_SPECS",
    "TRUE_NO_WRITEBACK_ACTION",
    "DEFAULT_RUNTIME_ACTION_DISPATCHER",
    "RuntimeActionDispatcher",
    "UnsupportedRuntimeActionError",
    "WARM_START_ACTION_SPECS",
    "apply_budget_reallocation_action",
    "apply_legacy_shared_variable_policy",
    "apply_shared_variable_action",
    "apply_sweep_ordering_action",
    "apply_warm_start_action",
    "blend_overlap_values",
    "budget_allocation_anchor_hash",
    "budget_allocation_parameter_hash",
    "clipped_consensus_blend",
    "controller_action_effects",
    "controller_has_capability",
    "controller_profile_by_action",
    "controller_profile_by_lane",
    "controller_profile_by_version",
    "execute_full_space_sep_cma_action",
    "full_space_sep_cma_anchor_hash",
    "full_space_vector_hash",
    "execute_budget_allocation_action",
    "execute_persistent_budget_allocation_action",
    "resolve_group_optimizer_action",
]
