"""Identity-blind Phase-I evidence collection."""

from arac.evidence.hierarchical import (
    EVIDENCE_MODES,
    MIN_SIGN_STABILITY,
    Phase1Evidence,
    RegionNode,
    RegionRelation,
    RegionStructure,
    RegionTree,
    ResolvedOverlapHyperedge,
    VARIABLE_STATUSES,
    VariableRegionInteraction,
    mode_of_component,
    to_overlap_structure,
)
from arac.evidence.overlap_adapter import (
    INFERENCE_INCOMPLETE,
    INFERENCE_READY,
    PARTITION_ONLY_REASON,
    Phase1OverlapAdaptation,
    Phase1OverlapAdapter,
    Phase1OverlapEvidence,
)
from arac.evidence.overlap_discovery import (
    DEFAULT_EDGE_THRESHOLD,
    DEFAULT_MIN_SUPPORT,
    OverlapDiscoveryResult,
    discover_overlap,
)
from arac.evidence.sparse_overlap_discovery import (
    DEFAULT_BUCKET_SIZE,
    DEFAULT_MAX_CANDIDATE_PAIRS,
    DEFAULT_SPARSE_MIN_SUPPORT,
    DEFAULT_SPARSE_ROUNDS,
    SparseOverlapDiscoveryResult,
    discover_overlap_sparse,
)
from arac.evidence.phase1 import (
    PHASE1_FEATURE_NAMES,
    PHASE1_FES,
    PHASE1_MIN_FES,
    PHASE1_PROTOCOL,
    PROGRESS_FEATURE_NAMES,
    Phase1Probe,
    phase1_budget,
    run_phase1,
)
from arac.evidence.phase1_overlap_pilot import (
    PHASE1_OVERLAP_PILOT_PROTOCOL,
    Phase1OverlapPilotResult,
    run_phase1_overlap_pilot,
)

__all__ = [
    "EVIDENCE_MODES",
    "MIN_SIGN_STABILITY",
    "Phase1Evidence",
    "RegionNode",
    "RegionRelation",
    "RegionStructure",
    "RegionTree",
    "ResolvedOverlapHyperedge",
    "VARIABLE_STATUSES",
    "VariableRegionInteraction",
    "mode_of_component",
    "to_overlap_structure",
    "INFERENCE_INCOMPLETE",
    "INFERENCE_READY",
    "PARTITION_ONLY_REASON",
    "PHASE1_FEATURE_NAMES",
    "PHASE1_FES",
    "PHASE1_MIN_FES",
    "PHASE1_PROTOCOL",
    "PROGRESS_FEATURE_NAMES",
    "Phase1OverlapAdaptation",
    "Phase1OverlapAdapter",
    "Phase1OverlapEvidence",
    "DEFAULT_EDGE_THRESHOLD",
    "DEFAULT_MIN_SUPPORT",
    "OverlapDiscoveryResult",
    "discover_overlap",
    "DEFAULT_BUCKET_SIZE",
    "DEFAULT_MAX_CANDIDATE_PAIRS",
    "DEFAULT_SPARSE_MIN_SUPPORT",
    "DEFAULT_SPARSE_ROUNDS",
    "SparseOverlapDiscoveryResult",
    "discover_overlap_sparse",
    "Phase1Probe",
    "phase1_budget",
    "run_phase1",
    "PHASE1_OVERLAP_PILOT_PROTOCOL",
    "Phase1OverlapPilotResult",
    "run_phase1_overlap_pilot",
]
